language: php

# Use container-based infrastructure
sudo: false

php:
  - 7.0
  - 7.1

before_script:
  - composer self-update
  - composer install

#script: vendor/bin/phpunit
#
#after_success:
# - wget https://github.com/php-coveralls/php-coveralls/releases/download/v1.0.1/coveralls.phar -O coveralls.phar
# - php coveralls.phar -v

notifications:
  email: false
